# Generated by Django 3.1.1 on 2020-09-19 15:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
import general.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=60)),
                ('adresse', models.CharField(max_length=250)),
                ('code_postal', models.CharField(max_length=5)),
                ('commune', models.CharField(max_length=100)),
                ('societe_manege', models.CharField(blank=True, max_length=150, null=True, verbose_name='Société - Manège')),
                ('telephone', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
                'unique_together': {('nom', 'societe_manege')},
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('ville', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[(1, 'Fête foraine'), (2, 'Brocante'), (3, 'Cirque'), (4, 'Autre')], max_length=50, verbose_name="Type d'évènement")),
            ],
            options={
                'verbose_name': 'Evènement',
                'verbose_name_plural': 'Evènements',
            },
        ),
        migrations.CreateModel(
            name='Saison',
            fields=[
                ('nom', models.CharField(default=general.models.get_default_periode_name, max_length=50, primary_key=True, serialize=False)),
                ('date_debut', models.DateField(default=datetime.datetime.now, verbose_name='Début de la saison')),
                ('date_fin', models.DateField(default=general.models.get_default_interval, verbose_name='Fin de la saison')),
                ('nb_jours', models.IntegerField(default=23, verbose_name='Nombre de jours')),
            ],
            options={
                'verbose_name': 'Période',
                'verbose_name_plural': 'Périodes',
            },
        ),
        migrations.CreateModel(
            name='InfosTechniques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule_compteur', models.CharField(blank=True, max_length=3, null=True)),
                ('num_armoire', models.CharField(max_length=5, verbose_name='numéro armoire')),
                ('emplacement', models.CharField(default=0, max_length=2)),
            ],
            options={
                'verbose_name': 'Informations Techniques',
                'verbose_name_plural': 'Informations Techniques',
                'unique_together': {('num_armoire', 'emplacement')},
            },
        ),
        migrations.CreateModel(
            name='Forfait',
            fields=[
                ('nom', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('prix_ht', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Prix HT')),
                ('prix_ttc', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Prix TTC')),
                ('taxe', models.DecimalField(decimal_places=2, default=20.0, max_digits=4)),
                ('saison', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.saison')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puissance', models.IntegerField(default=0, help_text='Puissance en KvA')),
                ('nb_jours', models.IntegerField(default=23, verbose_name='Nombre de jours')),
                ('total_ht', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('payee', models.BooleanField(default=False, verbose_name='Commade payée')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='general.client')),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.evenement')),
                ('forfait', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.forfait')),
                ('infos_techniques', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.infostechniques', verbose_name='Informations techniques')),
                ('saison', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.saison')),
            ],
        ),
    ]
