# Generated by Django 3.1.1 on 2020-09-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='infostechniques',
            name='num_armoire',
            field=models.CharField(max_length=5, verbose_name='numéro armoire'),
        ),
    ]
