# Generated by Django 3.1.2 on 2020-10-04 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Commande'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='traite_ach',
            field=models.BooleanField(default=False, verbose_name='Traitée ACH'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='type',
            field=models.CharField(choices=[('FF', 'Fête foraine'), ('BR', 'Brocante'), ('CR', 'Cirque'), ('AU', 'Autre')], max_length=50, verbose_name="Type d'évènement"),
        ),
    ]
