# Generated by Django 3.1.1 on 2020-09-17 07:34

import datetime
from django.db import migrations, models
import general.models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20200916_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saison',
            options={'verbose_name': 'Période', 'verbose_name_plural': 'Périodes'},
        ),
        migrations.RemoveField(
            model_name='saison',
            name='id',
        ),
        migrations.AddField(
            model_name='saison',
            name='date_debut',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='saison',
            name='date_fin',
            field=models.DateField(default=general.models.get_default_interval),
        ),
        migrations.AddField(
            model_name='saison',
            name='nb_jours',
            field=models.IntegerField(default=0, verbose_name='Nombre de jours'),
        ),
        migrations.AddField(
            model_name='saison',
            name='nom',
            field=models.CharField(default=general.models.get_default_periode_name, max_length=50, primary_key=True, serialize=False),
        ),
    ]
