# Generated by Django 3.1.1 on 2020-09-17 09:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
import general.models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20200917_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saison',
            name='date_debut',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Début de la saison'),
        ),
        migrations.AlterField(
            model_name='saison',
            name='date_fin',
            field=models.DateField(default=general.models.get_default_interval, verbose_name='Fin de la saison'),
        ),
        migrations.AlterField(
            model_name='saison',
            name='nb_jours',
            field=models.IntegerField(default=23, verbose_name='Nombre de jours'),
        ),
        migrations.CreateModel(
            name='Forfait',
            fields=[
                ('nom', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descrription', models.TextField()),
                ('prix_ht', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Prix HT')),
                ('prix_ttc', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Prix TTC')),
                ('taxe', models.DecimalField(decimal_places=2, default=20.0, max_digits=4)),
                ('saison', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.saison')),
            ],
        ),
    ]
