# Generated by Django 3.1.1 on 2020-09-17 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20200917_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forfait',
            old_name='descrription',
            new_name='description',
        ),
    ]
