# Generated by Django 3.1.1 on 2020-09-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_auto_20200917_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=60)),
                ('adresse', models.CharField(max_length=250)),
                ('code_postal', models.CharField(max_length=5)),
                ('commune', models.CharField(max_length=100)),
                ('societe_manege', models.CharField(blank=True, max_length=150, null=True, verbose_name='Société - Manège')),
                ('telephone', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
                'unique_together': {('nom', 'societe_manege')},
            },
        ),
    ]
