# Generated by Django 3.1.1 on 2020-09-18 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_auto_20200917_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=60)),
                ('adresse', models.CharField(max_length=250)),
                ('code_postal', models.CharField(max_length=5)),
                ('commune', models.CharField(max_length=100)),
                ('societe_manege', models.CharField(blank=True, max_length=150, null=True, verbose_name='Société - Manège')),
                ('telephone', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
                'unique_together': {('nom', 'societe_manege')},
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('ville', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[(1, 'Fête foraine'), (2, 'Brocante'), (3, 'Cirque'), (4, 'Autre')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puissance', models.IntegerField(default=0, help_text='Puissance en KvA')),
                ('nb_jours', models.IntegerField(default=23, verbose_name='Nombre de jours')),
                ('total_ht', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('payee', models.BooleanField(default=False, verbose_name='Commade payée')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='general.client')),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.evenement')),
                ('forfait', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.forfait')),
                ('infos_techniques', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.infostechniques', verbose_name='Informations techniques')),
                ('saison', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.saison')),
            ],
        ),
    ]
