# Generated by Django 3.1.1 on 2020-09-18 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_client_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='commande',
            name='infos_techniques',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.infostechniques', verbose_name='Informations techniques'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='nb_jours',
            field=models.IntegerField(default=23, verbose_name='Nombre de jours'),
        ),
    ]
